package view;

import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import java.io.FileOutputStream;
import java.util.Date;



public class LaporanKeuangann extends javax.swing.JInternalFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi ();

    public LaporanKeuangann() {
        initComponents();
        k.getConnection();
        pencarianMasuk();
        pencarianKeluar();
    }
    
    protected void pencarianMasuk() {
        Object[] Baris = {"Tanggal", "Total Harga Beli"};
        model = new DefaultTableModel(null, Baris);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String selectedDate = null;
        if (jDateChooser1.getDate() != null) {
            selectedDate = sdf.format(jDateChooser1.getDate()); 
        }

        try {
            String sql = "SELECT * FROM penjualan WHERE tanggal = ? ORDER BY tanggal ASC";
            PreparedStatement stat = k.getConnection().prepareStatement(sql);

            stat.setString(1, selectedDate != null ? selectedDate : ""); 

            ResultSet hasil = stat.executeQuery();

            while (hasil.next()) {
                model.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2)
                });
            }

            tblTampilan.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }
    
    
    protected void pencarianKeluar() {
        Object[] Baris = {"Tanggal", "Nama Barang", "Jenis Barang", "Jumlah","Harga Satuan", "Total Harga"};
        model = new DefaultTableModel(null, Baris);

        // Ambil data dari JDateChooser
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String selectedDate = null;
        if (jDateChooser2.getDate() != null) {
            selectedDate = sdf.format(jDateChooser2.getDate()); // Dapatkan tanggal
        }

        try {
            String sql = "SELECT * FROM tb_barang WHERE Tanggal = ? ORDER BY Tanggal ASC";
            PreparedStatement stat = k.getConnection().prepareStatement(sql);

            stat.setString(1, selectedDate != null ? selectedDate : ""); // Tanggal dari JDateChooser

            ResultSet hasil = stat.executeQuery();

            while (hasil.next()) {
                model.addRow(new Object[]{
                    hasil.getString(1), // Kolom 1
                    hasil.getString(2), // Kolom 2
                    hasil.getString(3), // Kolom 3
                    hasil.getString(4), // Kolom 4
                    hasil.getString(5), // Kolom 5
                    hasil.getString(6)
                });
            }

            // Set model ke JTable
            jTable2.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }
    

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTampilan = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtKeuntungan = new javax.swing.JTextField();
        txtTotalPendapatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("Laporan Keuangan");

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Transaksi Uang Masuk"));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Pencarian");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblTampilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tanggal", "Total Harga Beli"
            }
        ));
        tblTampilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTampilanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTampilan);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("Total Keuntungan");

        txtKeuntungan.setEnabled(false);
        txtKeuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeuntunganActionPerformed(evt);
            }
        });

        txtTotalPendapatan.setEnabled(false);
        txtTotalPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPendapatanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Total Pendapatan");

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Transaksi Uang Keluar"));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setText("Pencarian");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Nama Barang", "Jenis Barang", "Jumlah", "Harga Satuan", "Total Harga"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton5.setText("Hitung");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("Cetak Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setText("Simpan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtKeuntungan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKeuntungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblTampilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTampilanMouseClicked
        int bar = tblTampilan.getSelectedRow();
        String a = model.getValueAt(bar, 1).toString();
        String b = model.getValueAt(bar, 2).toString();
    }//GEN-LAST:event_tblTampilanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pencarianMasuk();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
    // Ambil tanggal dari jDateChooser
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(jDateChooser1.getDate()); // Format tanggal jadi "YYYY-MM-DD"

    // Query untuk menghitung total pendapatan berdasarkan tanggal tertentu
    this.stat = k.getConnection().prepareStatement(
        "SELECT SUM(total_harga) AS TotalPendapatan FROM penjualan WHERE tanggal = ?"
    );

    // Set parameter tanggal pada query
    this.stat.setString(1, tanggal);

    // Eksekusi query
    ResultSet rs = this.stat.executeQuery();

    if (rs.next()) {
        int totalPendapatan = rs.getInt("TotalPendapatan");

        // Tampilkan total pendapatan ke dalam TextField atau dialog
        txtTotalPendapatan.setText("Rp " + totalPendapatan);

        JOptionPane.showMessageDialog(null, 
                " Rp " + totalPendapatan,
                "Informasi Pendapatan", 
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, 
                "Tidak ada data pendapatan untuk tanggal " + tanggal,
                "Informasi Pendapatan", 
                JOptionPane.WARNING_MESSAGE);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int bar = jTable2.getSelectedRow();
        String a = model.getValueAt(bar, 1).toString();
        String b = model.getValueAt(bar, 2).toString();
        String c = model.getValueAt(bar, 3).toString();
        String d = model.getValueAt(bar, 4).toString();
        String e = model.getValueAt(bar, 5).toString();
        String f = model.getValueAt(bar, 6).toString();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    pencarianKeluar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
    // Ambil tanggal dari jDateChooser
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(jDateChooser2.getDate()); // Ambil tanggal dalam format "YYYY-MM-DD"

    // Query untuk menghitung total keuntungan berdasarkan tanggal tertentu
    this.stat = k.getConnection().prepareStatement(
        "SELECT (SELECT SUM(total_harga) FROM penjualan WHERE tanggal = ?) - " +
        "(SELECT SUM(TotalHarga) FROM tb_barang WHERE Tanggal = ?) AS TotalKeuntungan"
    );

    // Set parameter tanggal pada query
    this.stat.setString(1, tanggal);
    this.stat.setString(2, tanggal);

    // Eksekusi query
    ResultSet rs = this.stat.executeQuery();

    if (rs.next()) {
        int totalKeuntungan = rs.getInt("TotalKeuntungan");

        // Tampilkan total keuntungan ke dalam TextField atau dialog
        txtKeuntungan.setText("Rp " + totalKeuntungan);

        JOptionPane.showMessageDialog(null, 
                " Rp " + totalKeuntungan,
                "Informasi Keuntungan", 
                JOptionPane.INFORMATION_MESSAGE);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String namaFile = JOptionPane.showInputDialog(null, "Masukkan nama file laporan:", "Nama File", JOptionPane.QUESTION_MESSAGE);
if (namaFile == null || namaFile.trim().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Nama file tidak boleh kosong!");
    return;  // Hentikan proses jika nama file kosong
}
String filePath = namaFile + ".pdf";

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String tanggal = sdf.format(new Date()); // Ganti dengan tanggal dari input

try (Connection conn = k.getConnection();
    FileOutputStream fos = new FileOutputStream(filePath)) {
    Document document = new Document();
    PdfWriter.getInstance(document, fos);
    document.open();

    // Judul
    // Load font Times New Roman
    BaseFont baseFont = BaseFont.createFont("C:/Windows/Fonts/times.ttf", BaseFont.WINANSI, BaseFont.EMBEDDED);
    Font customFont = new Font(baseFont, 16, Font.BOLD);

    // Buat judul laporan dengan font custom
    Paragraph title = new Paragraph("Laporan Keuangan untuk Tanggal: " + tanggal, customFont);
    title.setAlignment(Element.ALIGN_CENTER);

    // Tambahkan ke dokumen
    document.add(title);
    document.add(new Paragraph("\n")); // Spasi biar gak dempet

    // ======= TABEL PENDAPATAN =======
    PdfPTable tablePendapatan = new PdfPTable(2);  // 7 kolom untuk data transaksi
    tablePendapatan.setWidthPercentage(100);  // Mengatur lebar tabel agar 100% lebar halaman
    float[] columnWidths = {2f, 2f};  // Mengatur lebar setiap kolom
    tablePendapatan.setWidths(columnWidths);
    String[] headersPendapatan = {"Tanggal", "Total Harga Beli"};
    for (String header : headersPendapatan) {
        PdfPCell cell = new PdfPCell(new Phrase(header));
        cell.setBackgroundColor(BaseColor.PINK);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        tablePendapatan.addCell(cell);
    }
    
    double totalPendapatan = 0;
    double totalPengeluaran = 0;
    
    String queryPendapatan = "SELECT tanggal, total_harga FROM penjualan WHERE tanggal = ?";
    try (PreparedStatement stmt = conn.prepareStatement(queryPendapatan)) {
        stmt.setString(1, tanggal);
        ResultSet rs = stmt.executeQuery();
        boolean dataFound = false;
        while (rs.next()) {
            dataFound = true;
            tablePendapatan.addCell(rs.getString("tanggal"));
            tablePendapatan.addCell(rs.getString("total_harga"));
            totalPendapatan += rs.getDouble("total_harga");
        }
        if (!dataFound) {
        System.out.println("Tidak ada data untuk tanggal: " + tanggal);
        }
        document.add(tablePendapatan);
        
        // Menambahkan total pendapatan di bawah tabel
        Paragraph totalPendapatanPara = new Paragraph("Total Pendapatan: Rp " + totalPendapatan, new Font(baseFont, 12));
        totalPendapatanPara.setAlignment(Element.ALIGN_RIGHT);
        document.add(totalPendapatanPara);
    }

    document.add(new Paragraph("\n"));

    // ======= TABEL DATA BARANG =======
    PdfPTable tableBarang = new PdfPTable(6);  // 5 kolom untuk data barang
    tableBarang.setWidthPercentage(100);  // Mengatur lebar tabel agar 100% lebar halaman
    float[] columnWidthsBarang = {2f, 2f, 2f, 2f, 2f, 2f};  // Mengatur lebar setiap kolom
    tableBarang.setWidths(columnWidthsBarang);
    String[] headersBarang = {"Tanggal", "Nama Barang", "Jenis Barang", "Harga Satuan", "Jumlah", "Total Harga"};
    for (String header : headersBarang) {
        PdfPCell cell = new PdfPCell(new Phrase(header));
        cell.setBackgroundColor(BaseColor.PINK);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        tableBarang.addCell(cell);
    }

    String queryBarang = "SELECT Tanggal, NamaBarang, JenisBarang, HargaSatuan, Jumlah, TotalHarga FROM tb_barang WHERE Tanggal = ?";
    try (PreparedStatement stmt = conn.prepareStatement(queryBarang)) {
        stmt.setString(1, tanggal);
        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            tableBarang.addCell(rs.getString("Tanggal"));
            tableBarang.addCell(rs.getString("NamaBarang"));
            tableBarang.addCell(rs.getString("JenisBarang"));
            tableBarang.addCell(rs.getString("HargaSatuan"));
            tableBarang.addCell(rs.getString("Jumlah"));
            double totalPengeluaranItem = rs.getDouble("Jumlah") * rs.getDouble("HargaSatuan");
            tableBarang.addCell(String.valueOf(totalPengeluaranItem));
            totalPengeluaran += totalPengeluaranItem;
        }
        document.add(tableBarang);

        // Menambahkan total keuntungan di bawah tabel
        Paragraph totalPengeluaranPara = new Paragraph("Total Pengeluaran: Rp " + totalPengeluaran, new Font(baseFont, 12));
        totalPengeluaranPara.setAlignment(Element.ALIGN_RIGHT);
        document.add(totalPengeluaranPara);
    }
    
    double totalKeuntungan = totalPendapatan - totalPengeluaran;
    
    Paragraph totalKeuntunganPara = new Paragraph("Total Keuntungan: Rp " + totalKeuntungan, new Font(baseFont, 12));
    totalKeuntunganPara.setAlignment(Element.ALIGN_RIGHT);
    document.add(totalKeuntunganPara);

    document.close();
    JOptionPane.showMessageDialog(null, "Laporan berhasil dibuat: " + filePath);
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Gagal membuat laporan: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try {
    // Ambil nilai dari txtTotalPendapatan dan txtTotalKeuntungan
    String totalPendapatanText = txtTotalPendapatan.getText().replace("Rp", "").replace(" ", "");
    String totalKeuntunganText = txtKeuntungan.getText().replace("Rp", "").replace(" ", "");

    // Konversi string ke integer
    int totalPendapatan = Integer.parseInt(totalPendapatanText);
    int totalKeuntungan = Integer.parseInt(totalKeuntunganText);

    // Koneksi ke database
    Connection c = koneksi.getConnection();

    // Format tanggal dari jDateChooser1 dan jDateChooser2
    String tanggalPenjualan = null;
    String tanggalBarang = null;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    if (jDateChooser1.getDate() != null) {
        tanggalPenjualan = sdf.format(jDateChooser1.getDate());
    }
    if (jDateChooser2.getDate() != null) {
        tanggalBarang = sdf.format(jDateChooser2.getDate());
    }

    // Query untuk memasukkan data ke tabel laporankeuangan
    String sqltb_laporan = "INSERT INTO laporankeuangan (tanggalPenjualan, tanggalBarang, totalpendapatan, totalkeuntungan) VALUES (?, ?, ?, ?)";
    PreparedStatement pLaporan = c.prepareStatement(sqltb_laporan);

    // Set parameter
    pLaporan.setString(1, tanggalPenjualan); // Tanggal penjualan dari jDateChooser1
    pLaporan.setString(2, tanggalBarang);     // Tanggal barang dari jDateChooser2
    pLaporan.setInt(3, totalPendapatan);     // Total pendapatan
    pLaporan.setInt(4, totalKeuntungan);     // Total keuntungan

    // Eksekusi query
    pLaporan.executeUpdate();
    pLaporan.close();

    System.out.println("Data berhasil disimpan");
} catch (Exception e) {
    e.printStackTrace();
    System.err.println("Error saat menyimpan data");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtTotalPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPendapatanActionPerformed

    private void txtKeuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeuntunganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeuntunganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblTampilan;
    private javax.swing.JTextField txtKeuntungan;
    private javax.swing.JTextField txtTotalPendapatan;
    // End of variables declaration//GEN-END:variables
}
