package view;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.print.Printable;
import java.awt.print.PageFormat;
import java.awt.Graphics;


// Optional jika ingin menggunakan preview
// import net.sf.jasperreports.view.JasperViewer;

public class Transaksi extends javax.swing.JInternalFrame {
    
    String tanggal;
    private DefaultTableModel model ;
    
    public void totalBiaya(){
        int jumlahBaris= tblTampilan.getRowCount();
        int totalBiaya = 0;
        for (int i = 0; i < jumlahBaris; i++) {
            
            int totalHarga = Integer.parseInt(tblTampilan.getValueAt(i, 3).toString());
            totalBiaya += totalHarga;
        }
        txtTotalBayar.setText(String.valueOf(totalBiaya));
        txtTampil.setText("Rp. "+ totalBiaya +",00");
    }    

    public void kosong(){
        DefaultTableModel model = (DefaultTableModel) tblTampilan.getModel();
        
        while (model.getRowCount()>0){
            model.removeRow(0);
        }
    }
    
    public void loadData(){
        DefaultTableModel model = (DefaultTableModel) tblTampilan.getModel();
        model.addRow(new Object[]{
            cmdVariasi.getSelectedItem(),
            txtHarga.getText(),
            txtJumlah.getText(),
            txtTotalBayar.getText()
        });
    }
    
    public void utama(){
        Object selectedItem = cmdVariasi.getSelectedItem();
        if (selectedItem != null) {
            String variasiTerpilih = selectedItem.toString();
            System.out.println("Variasi yang dipilih: " + variasiTerpilih);
        } else {
            System.out.println("Tidak ada variasi yang dipilih.");
        }
        txtHarga.setText("");
        txtJumlah.setText("");
    }
    
    public void clear(){
        txtTotalBayar.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
        txtTampil.setText("");
    }
       
    public void clear2(){
        // Mendapatkan item yang dipilih pada cmdVariasi
        Object selectedItem = cmdVariasi.getSelectedItem();
        if (selectedItem != null) {
            String variasiTerpilih = selectedItem.toString();
            System.out.println("Variasi yang dipilih: " + variasiTerpilih);
        } else {
            System.out.println("Tidak ada variasi yang dipilih.");
        }
        txtHarga.setText("");
        txtJumlah.setText("");
    }
    
    public void tambahTransaksi(){
        int harga, jumlah_beli, total_harga;
        
        harga = Integer.valueOf(txtHarga.getText());
        jumlah_beli = Integer.valueOf(txtJumlah.getText());
        total_harga = harga * jumlah_beli;
        
        txtTotalBayar.setText(String.valueOf(total_harga));
        
        loadData();
        totalBiaya();
    }

    public Transaksi() {
        initComponents();
        
        //create table
        model = new DefaultTableModel();
        
        tblTampilan.setModel(model);
        
        model.addColumn("Variasi");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Harga");
        
        utama();
        Date date =  new Date();
        SimpleDateFormat s =  new SimpleDateFormat("yyyy-MM-dd");
        
        dateTanggal.setDate(new java.util.Date());
        txtTotalBayar.setText("");
        txtbayar.setText("");
        txtkembalian.setText("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cetakStruk = new javax.swing.JPanel();
        dateTanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdVariasi = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTampilan = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtTampil = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        cetakStruk.setBackground(new java.awt.Color(255, 204, 204));

        dateTanggal.setDate(new Date());
        dateTanggal.setDateFormatString("dd-MM-yyyy");
        dateTanggal.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Total Bayar");

        txtTotalBayar.setEditable(false);
        txtTotalBayar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });

        btnInput.setBackground(new java.awt.Color(204, 204, 204));
        btnInput.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtHarga.setEditable(false);
        txtHarga.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Penjualan");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Variasi");

        cmdVariasi.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cmdVariasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Orange Iced Tea", "Vanilla Iced Tea", "Thai Iced Tea", "Lemon Honey Iced Tea", "Chocolate Iced Tea", "Lychee Iced Tea", "Cappucino Iced Tea", "Mango Iced Tea", "Apple Iced Tea" }));
        cmdVariasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVariasiActionPerformed(evt);
            }
        });

        txtJumlah.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah ");

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tblTampilan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tblTampilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Variasi", "Harga", "Jumlah Beli", "Total Harga"
            }
        ));
        tblTampilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTampilanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTampilan);

        jScrollPane3.setViewportView(jScrollPane2);

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btn_delete.setText("Dalete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Bayar");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setText("Kembalian");

        txtkembalian.setEditable(false);
        txtkembalian.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });

        txtbayar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbayarKeyPressed(evt);
            }
        });

        txtTampil.setEditable(false);
        txtTampil.setBackground(new java.awt.Color(204, 204, 204));
        txtTampil.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtTampil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTampil.setText("Rp. 0");
        txtTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTampilActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cetakStrukLayout = new javax.swing.GroupLayout(cetakStruk);
        cetakStruk.setLayout(cetakStrukLayout);
        cetakStrukLayout.setHorizontalGroup(
            cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakStrukLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cetakStrukLayout.createSequentialGroup()
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnInput)
                                .addGroup(cetakStrukLayout.createSequentialGroup()
                                    .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(cetakStrukLayout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_delete)))))
                    .addGroup(cetakStrukLayout.createSequentialGroup()
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(62, 62, 62)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cetakStrukLayout.createSequentialGroup()
                                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmdVariasi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(154, 154, 154))
                            .addGroup(cetakStrukLayout.createSequentialGroup()
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45)))
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetakStrukLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(368, 368, 368))
        );
        cetakStrukLayout.setVerticalGroup(
            cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakStrukLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmdVariasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cetakStrukLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetakStrukLayout.createSequentialGroup()
                        .addComponent(btnInput)
                        .addGap(18, 18, 18)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(cetakStrukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btn_delete))
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cetakStruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdVariasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVariasiActionPerformed
        String nama_variasi;
        int harga;
        if(cmdVariasi.getSelectedItem().toString()=="Orange Iced Tea"){
            nama_variasi="Orange Iced Tea";
            harga=7000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Lemon Honey Iced Tea"){
            nama_variasi="Lemon Honey Iced Tea";
            harga=7000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Lychee Iced Tea"){
            nama_variasi="Lychee Iced Tea";
            harga=7000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Mango Iced Tea"){
            nama_variasi="Mango Iced Tea";
            harga=7000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Apple Iced Tea"){
            nama_variasi="Apple Iced Tea";
            harga=7000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Vanilla Iced Tea"){
            nama_variasi="Vanilla Iced Tea";
            harga=5000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Vanilla Iced Tea"){
            nama_variasi="Vanilla Iced Tea";
            harga=5000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Thai Iced Tea"){
            nama_variasi="Thai Iced Tea";
            harga=10000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Chocolate Iced Tea"){
            nama_variasi="Chocolate Iced Tea";
            harga=8000;
            this.txtHarga.setText(""+harga);
        }if(cmdVariasi.getSelectedItem().toString()=="Cappucino Iced Tea"){
            nama_variasi="Cappucino Iced Tea";
            harga=8000;
            this.txtHarga.setText(""+harga);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdVariasiActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
    tambahTransaksi();
    clear2();
    }//GEN-LAST:event_btnInputActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void tblTampilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTampilanMouseClicked
        cmdVariasi.setSelectedItem(model.getValueAt(tblTampilan.getSelectedRow(),0).toString());
        txtHarga.setText(model.getValueAt(tblTampilan.getSelectedRow(),1).toString());
        txtJumlah.setText(model.getValueAt(tblTampilan.getSelectedRow(),2).toString());
        txtTotalBayar.setText(model.getValueAt(tblTampilan.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tblTampilanMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
tambahTransaksi();    // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblTampilan.getModel();
        int row = tblTampilan.getSelectedRow();
        model.removeRow(row);
        totalBiaya();
        cmdVariasi.getSelectedItem();
        txtHarga.setText("");
        txtJumlah.setText("");
        txtbayar.setText("0");
        txtkembalian.setText("0");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        int total_harga, bayar, kembalian;
        
        total_harga = Integer.valueOf(txtTotalBayar.getText());
        bayar = Integer.valueOf(txtbayar.getText());
        
        if (total_harga > bayar) {
            JOptionPane.showMessageDialog(null, "Uang tidak cukup untuk melakukan pembayaran");
        } else {
            kembalian = bayar - total_harga;
            txtkembalian.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarKeyPressed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
    tambahTransaksi();  
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblTampilan.getModel();

    String tanggal;
    if (dateTanggal.getDate() != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tanggal = sdf.format(dateTanggal.getDate());
    } else {
        tanggal = null;
    }

    String total_harga = txtTotalBayar.getText();
    String uang_bayar = txtbayar.getText();
    String uang_kembalian;

        // Validasi input
        if (tanggal == null || total_harga.isEmpty() || uang_bayar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Konversi string ke integer untuk menghitung uang kembalian
            int totalHarga = Integer.parseInt(total_harga);
            int uangBayar = Integer.parseInt(uang_bayar);

            // Hitung uang kembalian
            int kembalian = uangBayar - totalHarga;
            uang_kembalian = String.valueOf(kembalian);

            // Cek apakah uang bayar cukup
            if (kembalian < 0) {
                JOptionPane.showMessageDialog(this, "Uang bayar tidak cukup!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Simpan ke database
            Connection c = koneksi.getConnection();
            String sql = "INSERT INTO penjualan (tanggal, total_harga, uang_bayar, uang_kembalian) VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, tanggal);
            p.setInt(2, totalHarga);
            p.setInt(3, uangBayar);
            p.setInt(4, kembalian);

            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(this, "Data penjualan berhasil disimpan!");

            // Bersihkan input setelah menyimpan
            txtTotalBayar.setText("");
            txtbayar.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pastikan Total Harga dan Uang Bayar adalah angka valid!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            System.err.println("Simpan penjualan error: " + e.getMessage());
        }

        
        try {
            Connection c = koneksi.getConnection();
            int baris = tblTampilan.getRowCount();
            
            for (int i = 0; i < baris; i++) {
                String sql = "INSERT INTO rincianpenjualan (nama_variasi, harga, jumlah_beli, total_harga) VALUES ('"
                        + tblTampilan.getValueAt(i, 0) +"','"+ tblTampilan.getValueAt(i, 1) +"','"+ tblTampilan.getValueAt(i, 2)
                        +"','"+ tblTampilan.getValueAt(i, 3) +"')";
                PreparedStatement p = c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Simpan rincianpenjualan error");
        }
        utama();
        clear();
        kosong();
        txtTampil.setText("Rp. 0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTampilActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtTampilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PrinterJob job = PrinterJob.getPrinterJob();
    job.setPrintable(new Printable() {
        @Override
        public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
            if (pageIndex > 0) {
                return NO_SUCH_PAGE;
            }

            // Mengatur posisi dan ukuran untuk mencetak
            g.drawString("================================", 100, 100);
            g.drawString("Struk Transaksi", 100, 120);
            g.drawString("Tanggal: " + new SimpleDateFormat("dd-MM-yyyy").format(dateTanggal.getDate()), 100, 140);
            g.drawString("Variasi        Harga     Jumlah     Total", 100, 160);
            g.drawString("================================", 100, 180);

            // Menampilkan data dari tabel
            for (int i = 0; i < tblTampilan.getRowCount(); i++) {
                String variasi = tblTampilan.getValueAt(i, 0).toString();
                String harga = tblTampilan.getValueAt(i, 1).toString();
                String jumlah = tblTampilan.getValueAt(i, 2).toString();
                String total = tblTampilan.getValueAt(i, 3).toString();
                g.drawString(variasi + "        " + harga + "     " + jumlah + "     " + total, 100, 200 + (i * 20));
            }

            g.drawString("================================", 100, 200 + (tblTampilan.getRowCount() * 20));
            g.drawString("Total Bayar: " + txtTotalBayar.getText(), 100, 220 + (tblTampilan.getRowCount() * 20));
            g.drawString("Bayar: " + txtbayar.getText(), 100, 240 + (tblTampilan.getRowCount() * 20));
            g.drawString("Kembalian: " + txtkembalian.getText(), 100, 260 + (tblTampilan.getRowCount() * 20));
            g.drawString("================================", 100, 280 + (tblTampilan.getRowCount() * 20));
            g.drawString("Terima kasih!", 100, 300 + (tblTampilan.getRowCount() * 20));

            return PAGE_EXISTS;
        }
    });

    // Menampilkan dialog untuk memilih printer
    if (job.printDialog()) {
        try {
            job.print();
        } catch (PrinterException e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi ().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btn_delete;
    private javax.swing.JPanel cetakStruk;
    private javax.swing.JComboBox<String> cmdVariasi;
    private com.toedter.calendar.JDateChooser dateTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTampilan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTampil;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtkembalian;
    // End of variables declaration//GEN-END:variables
}
